### ISSUE TITLE
Is binding on 0.0.0.0:8080 safe?

### ISSUE THREAD

**Issue by DrWhax** [ICIJ/datashare-installer#2]
I'm not entirely sure what's the threat model of datashare, but binding automatically on 0.0.0.0:8080 is maybe not super advisable, as anyone on the same network can see what the researcher/journalist has indexed.. hopefully the networks are vlan'd or not connected to a network, but yeah, better safe than sorry.

**Comment by bamthomas** [comment]
yes good point. It has been fixed with the 6e86bc673e48cb004168c7478287b529c0e557e9 commit (version 1.64.0)
