### ISSUE TITLE
empty database

### ISSUE THREAD

**Issue by francescor** [ICIJ/datashare-installer#3]
just installed datashare_version="4.10.2", everything fine, but /home/danny/Datashare is empty (and research returns no data); should I download something else? 

```
Docker version 19.03.2
Fedora release 29
```

**Comment by pirhoo** [comment]
Hi @francescor, Datashare doesn't come with any data. It's a tool to analyse and search through your own documents.

**Comment by annelhote** [comment]
Just like @pirhoo said, Datashare is made to analyze your own documents. To do so, put those documents in this folder "/home/danny/Datashare" and launch the analyze like explained here : https://icij.gitbook.io/datashare/all/analyze-documents.
